# Generated by Django 5.2.5 on 2025-08-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0004_profile_profile_name_alter_profile_cover_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
