# Generated by Django 5.2.5 on 2025-08-31 08:14

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0005_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='body'),
        ),
    ]
